version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/choria-io/mcorpc-agent-provider

    environment:
      GO111MODULE: "on"

    steps:
      - checkout

      - run: go get github.com/onsi/ginkgo/ginkgo
      - run: ginkgo -r -skipMeasurements mcorpc
